#! /usr/bin/env python
#
# Support module generated by PAGE version 4.2.2a
# In conjunction with Tcl version 8.6
#    Mar. 28, 2014 03:22:46 PM


import sys
import subprocess

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


def quit():
        print ('cpu_info_support.quit')
        sys.stdout.flush()
        sys.exit()

def init(top, gui, arg=None):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    load_cpu_info()

def destroy_window ():
    # Function which closes the window.import subprocess
    global top_level
    top_level.destroy()
    top_level = None

def load_cpu_info():
    global w
    obj = w.Scrolledtext1
    obj.delete(1.0,END)
    proc = subprocess.Popen('lscpu', stdout=subprocess.PIPE, shell=True)
    (out, err) = proc.communicate()
    obj.insert(END, out)
