#############################################################################
# Generated by PAGE version 4.2
# in conjunction with Tcl version 8.6
#    Jan. 27, 2014 12:16:35 AM


vTcl:font:add_GUI_font font10 \
"-family {DejaVu Sans} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font font11 \
"-family {Droid Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) wheat
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) wheat
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #111111
#############################################################################
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top34
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    set site_4_0 .top34.tPa35.f1 
    set site_4_1 .top34.tPa35.f2 
    set site_4_0 $site_4_1
    set site_6_0 .top34.tPa35.f2.tPa36.f1 
    set site_6_1 .top34.tPa35.f2.tPa36.f2 
    set site_6_0 $site_6_1
    set site_8_0 .top34.tPa35.f2.tPa36.f2.tNo37.pg0 
    set site_8_0 $site_8_0
    set site_8_1 .top34.tPa35.f2.tPa36.f2.tNo37.pg1 
    set site_8_0 $site_8_1
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow. {base} {
    if {$base == ""} {
        set base .
    }
    ###################
    # CREATING WIDGETS
    ###################
    wm focusmodel $top passive
    wm geometry $top 1x1+0+0; update
    wm maxsize $top 1905 1170
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm withdraw $top
    wm title $top "page.tcl"
    bindtags $top "$top Page.tcl all"
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top34 {base} {
    if {$base == ""} {
        set base .top34
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -background wheat -highlightbackground wheat -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x478+650+150; update
    wm maxsize $top 1905 1170
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Complex example"
    bindtags $top "$top Toplevel all _TopLevel"
    ttk::style configure TPanedwindow -background wheat
    ttk::style configure TPanedwindow.Label -background wheat
    ttk::style configure TPanedwindow.Label -foreground #000000
    ttk::style configure TPanedwindow.Label -font font10
    ttk::panedwindow $top.tPa35 \
        -width 200 -height 200 
    vTcl:DefineAlias "$top.tPa35" "TPanedwindow1" vTcl:WidgetProc "$top" 1
    ttk::style configure TLabelframe.Label -background wheat
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font font10
    ttk::style configure TLabelframe -background wheat
    ttk::labelframe $top.tPa35.f1 \
        -text {Pane 1} -width 200 -height 75 
    set site_4_0 $top.tPa35.f1
    $top.tPa35 add $top.tPa35.f1 
        
    ttk::style configure TLabelframe.Label -background wheat
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font font10
    ttk::style configure TLabelframe -background wheat
    ttk::labelframe $top.tPa35.f2 \
        -text {Pane 2} -width 200 -height 125 
    set site_4_1 $top.tPa35.f2
    ttk::style configure TPanedwindow -background wheat
    ttk::style configure TPanedwindow.Label -background wheat
    ttk::style configure TPanedwindow.Label -foreground #000000
    ttk::style configure TPanedwindow.Label -font font10
    ttk::panedwindow $site_4_1.tPa36 \
        -orient horizontal -width 200 -height 200 
    vTcl:DefineAlias "$site_4_1.tPa36" "TPanedwindow2" vTcl:WidgetProc "$top" 1
    ttk::style configure TLabelframe.Label -background wheat
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font font10
    ttk::style configure TLabelframe -background wheat
    ttk::labelframe $site_4_1.tPa36.f1 \
        -text {Pane 1} -width 75 -height 200 
    set site_6_0 $site_4_1.tPa36.f1
    $site_4_1.tPa36 add $site_4_1.tPa36.f1 
        
    ttk::style configure TLabelframe.Label -background wheat
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font font10
    ttk::style configure TLabelframe -background wheat
    ttk::labelframe $site_4_1.tPa36.f2 \
        -text {Pane 2} -width 125 -height 200 
    set site_6_1 $site_4_1.tPa36.f2
    ttk::style configure TNotebook -background wheat
    ttk::style configure TNotebook.Tab -background wheat
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font font10
    ttk::style map TNotebook.Tab -background [list disabled wheat selected #b2c9f4]
    ttk::notebook $site_6_1.tNo37 \
        -width 300 -height 200 -takefocus {} 
    vTcl:DefineAlias "$site_6_1.tNo37" "TNotebook1" vTcl:WidgetProc "$top" 1
    frame .top34.tPa35.f2.tPa36.f2.tNo37.pg0 -background wheat
    $site_6_1.tNo37 add .top34.tPa35.f2.tPa36.f2.tNo37.pg0 \
        -padding 0 -sticky nsew -state normal -text {Page 1} -image {} \
        -compound none -underline -1 
    set site_8_0  $site_6_1.tNo37.pg0
    label $site_8_0.lab38 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#b8a786} -font font10 -foreground {#000000} \
        -highlightbackground wheat -highlightcolor black -text {First Page} 
    vTcl:DefineAlias "$site_8_0.lab38" "Label1" vTcl:WidgetProc "$top" 1
    button $site_8_0.but34 \
        -activebackground {#f4bcb2} -background wheat -command qqq \
        -disabledforeground {#b8a786} -font font10 -foreground {#000000} \
        -highlightbackground wheat -highlightcolor black -text Button \
        -textvariable zzz 
    vTcl:DefineAlias "$site_8_0.but34" "Button2" vTcl:WidgetProc "$top" 1
    place $site_8_0.lab38 \
        -in $site_8_0 -x 50 -y 50 -anchor nw -bordermode ignore 
    place $site_8_0.but34 \
        -in $site_8_0 -x 90 -y 100 -anchor nw -bordermode ignore 
    frame .top34.tPa35.f2.tPa36.f2.tNo37.pg1 -background wheat
    $site_6_1.tNo37 add .top34.tPa35.f2.tPa36.f2.tNo37.pg1 \
        -padding 0 -sticky nsew -state normal -text {Page 2} -image {} \
        -compound none -underline -1 
    set site_8_1  $site_6_1.tNo37.pg1
    label $site_8_1.lab39 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#b8a786} -font font10 -foreground {#000000} \
        -highlightbackground wheat -highlightcolor black -text {Second Page} 
    vTcl:DefineAlias "$site_8_1.lab39" "Label2" vTcl:WidgetProc "$top" 1
    place $site_8_1.lab39 \
        -in $site_8_1 -x 100 -y 90 -anchor nw -bordermode ignore 
    place $site_6_1.tNo37 \
        -in $site_6_1 -x 40 -y 40 -anchor nw -bordermode ignore 
    $site_4_1.tPa36 add $site_4_1.tPa36.f2 
        
    place $site_4_1.tPa36 \
        -in $site_4_1 -x 40 -y 30 -width 460 -height 280 -anchor nw \
        -bordermode ignore 
    $top.tPa35 add $top.tPa35.f2 
        
    button $top.but40 \
        -activebackground {#f4bcb2} -activeforeground black -background wheat \
        -command quit -disabledforeground {#b8a786} -font font10 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text Quit 
    vTcl:DefineAlias "$top.but40" "Button1" vTcl:WidgetProc "$top" 1
    ttk::style configure TSizegrip -background wheat
    vTcl::widgets::ttk::sizegrip::CreateCmd $top.tSi34 \
        -cursor bottom_right_corner 
    vTcl:DefineAlias "$top.tSi34" "TSizegrip1" vTcl:WidgetProc "$top" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tPa35 \
        -in $top -x 30 -y 20 -width 540 -height 410 -anchor nw \
        -bordermode ignore 
    place $top.but40 \
        -in $top -x 220 -y 440 -anchor nw -bordermode ignore 
    place $top.tSi34 \
        -in $top -x 0 -relx 1 -y 0 -rely 1 -anchor se -bordermode inside 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top34

