#! /usr/bin/env python
#
# Support module generated by PAGE version 4.2
# In conjunction with Tcl version 8.6
#    Jan. 27, 2014 12:16:28 AM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global zzz
    zzz = StringVar()
    zzz.set('Buried')


def qqq():
        print ('complex_support.qqq')
        sys.stdout.flush()

def quit():
    sys.exit()

def init(top, gui):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window ():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


