float angle_shift ( float alpha, float beta );
float arccos_cordic ( float t, int n );
void arccos_values ( int *n_data, float *x, float *fx );
float arcsin_cordic ( float t, int n );
void arcsin_values ( int *n_data, float *x, float *fx );
float arctan_cordic ( float x, float y, int n );
void arctan_values ( int *n_data, float *x, float *fx );
float cbrt_cordic ( float x, int n );
void cbrt_values ( int *n_data, float *x, float *fx );
void cos_values ( int *n_data, float *x, float *fx );
void cossin_cordic ( float beta, int n, float *c, float *s );
float exp_cordic ( float x, int n );
void exp_values ( int *n_data, float *x, float *fx );
int i4_huge ( void );
int i4_min ( int i1, int i2 );
float ln_cordic ( float x, int n );
void ln_values ( int *n_data, float *x, float *fx );
float r8_uniform_01 ( int *seed );
void sin_values ( int *n_data, float *x, float *fx );
float sqrt_cordic ( float x, int n );
void sqrt_values ( int *n_data, float *x, float *fx );
float tan_cordic ( float beta, int n );
void tan_values ( int *n_data, float *x, float *fx );
void timestamp ( void );
