#! /usr/bin/env python
#
# Support module generated by PAGE version 4.2g
# In conjunction with Tcl version 8.6
#    Feb. 01, 2014 09:21:20 AM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import called

p_dict_1 = {'geom': "+200+650", 'instance': 1, 'color' : 'firebrick'}
p_dict_2 = {'geom': "+1000+650", 'instance': 2, 'color' : 'plum'}


def open_two():
    print "open_two starts"
    firebrick = called.create_Called(root,param=p_dict_1)
    plum = called.create_Called(root,param=p_dict_2)


def quit():
    sys.exit()

def init(top, gui, arg=None):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window ():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


