#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.2.5a
# In conjunction with Tcl version 8.6
#    May. 17, 2014 11:37:48 AM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import button_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('Button_Example')
    root.geometry('600x450+650+150')
    w = Button_Example (root)
    button_support.init(root, w)
    root.mainloop()

w = None
def create_Button_Example (root, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w.title('Button_Example')
    w.geometry('600x450+650+150')
    w_win = Button_Example (w)
    button_support.init(w, w_win, param)
    return w_win

def destroy_Button_Example ():
    global w
    w.destroy()
    w = None


class Button_Example:
    def __init__(self, master=None):
        _bgcolor = 'wheat'  # X11 color: #f5deb3
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#b2c9f4' # Closest X11 color: 'SlateGray2'
        _ana1color = '#eaf4b2' # Closest X11 color: '{pale goldenrod}'
        _ana2color = '#f4bcb2' # Closest X11 color: 'RosyBrown2'
        font10 = "-family {DejaVu Sans} -size 14 -weight normal -slant " + \
            " roman -underline 0 -overstrike 0"
        master.configure(background=_bgcolor)
        master.configure(highlightbackground="wheat")
        master.configure(highlightcolor="black")


        self.Button1 = Button (master)
        self.Button1.place(relx=0.38,rely=0.27,height=65,width=123)
        self.Button1.configure(activebackground="#f4bcb2")
        self.Button1.configure(background=_bgcolor)
        self.Button1.configure(command=button_support.quit)
        self.Button1.configure(compound="top")
        self.Button1.configure(disabledforeground="#b8a786")
        self.Button1.configure(font=font10)
        self.Button1.configure(highlightbackground="wheat")
        self._img1 = PhotoImage(file="./stop.gif")
        self.Button1.configure(image=self._img1)
        self.Button1.configure(text='''Push to Quit''')





if __name__ == '__main__':
    vp_start_gui()



