#############################################################################
# Generated by PAGE version 4.2
# in conjunction with Tcl version 8.6
#    Feb. 12, 2014 08:53:18 PM


vTcl:font:add_GUI_font font10 \
"-family {DejaVu Sans} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font font11 \
"-family {Droid Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) wheat
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #111111
#############################################################################
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top34
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow. {base} {
    if {$base == ""} {
        set base .
    }
    ###################
    # CREATING WIDGETS
    ###################
    wm focusmodel $top passive
    wm geometry $top 1x1+0+0; update
    wm maxsize $top 1905 1170
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm withdraw $top
    wm title $top "page.tcl"
    bindtags $top "$top Page.tcl all"
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top34 {base} {
    if {$base == ""} {
        set base .top34
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground wheat \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x716+650+150; update
    wm maxsize $top 1905 1170
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    bindtags $top "$top Toplevel all _TopLevel"
    message $top.mes35 \
        -background {#d9d9d9} -font font10 -foreground {#000000} \
        -highlightbackground wheat -highlightcolor black -text Message \
        -width 90 
    vTcl:DefineAlias "$top.mes35" "Message1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra36 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 75 \
        -highlightbackground wheat -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.fra36" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can37 \
        -background white -borderwidth 2 -closeenough 1.0 -height 231 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 330 
    vTcl:DefineAlias "$top.can37" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but38 \
        -activebackground {#f4bcb2} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#b8a786} -font font10 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text Button 
    vTcl:DefineAlias "$top.but38" "Button1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent39 \
        -background white -disabledforeground {#b8a786} -font font11 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -insertbackground black \
        -selectbackground {#ddc8a1} -selectforeground black 
    vTcl:DefineAlias "$top.ent39" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab40 \
        -activebackground {#ffffcd} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#b8a786} -font font10 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab40" "Label1" vTcl:WidgetProc "Toplevel1" 1
    listbox $top.lis41 \
        -background white -disabledforeground {#b8a786} -font font11 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -selectbackground {#ddc8a1} \
        -selectforeground black 
    .top34.lis41 configure -font font11
    vTcl:DefineAlias "$top.lis41" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex42 \
        -background white -font font10 -foreground black -height 10 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 20 -wrap word 
    .top34.tex42 configure -font font10
    .top34.tex42 insert end text
    vTcl:DefineAlias "$top.tex42" "Text1" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che43 \
        -activebackground {#f4bcb2} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#b8a786} -font font10 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text Check -variable che43 
    vTcl:DefineAlias "$top.che43" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $top.rad44 \
        -activebackground {#f4bcb2} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#b8a786} -font font10 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text Radio -variable {} 
    vTcl:DefineAlias "$top.rad44" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    scale $top.sca45 \
        -activebackground {#f4bcb2} -background {#d9d9d9} -bigincrement 0.0 \
        -font font10 -foreground {#000000} -from 0.0 \
        -highlightbackground wheat -highlightcolor black -orient horizontal \
        -resolution 1.0 -tickinterval 0.0 -to 100.0 -troughcolor {#d9d9d9} 
    vTcl:DefineAlias "$top.sca45" "Scale1" vTcl:WidgetProc "Toplevel1" 1
    spinbox $top.spi46 \
        -activebackground {#f9f9f9} -background white -buttonbackground wheat \
        -disabledforeground {#b8a786} -font font10 -foreground black \
        -from 1.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$top.spi46" "Spinbox1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.mes35 \
        -in $top -x 90 -y 30 -anchor nw -bordermode ignore 
    place $top.fra36 \
        -in $top -x 90 -y 60 -anchor nw -bordermode ignore 
    place $top.can37 \
        -in $top -x 70 -y 160 -anchor nw -bordermode ignore 
    place $top.but38 \
        -in $top -x 300 -y 40 -anchor nw -bordermode ignore 
    place $top.ent39 \
        -in $top -x 300 -y 90 -anchor nw -bordermode ignore 
    place $top.lab40 \
        -in $top -x 440 -y 40 -anchor nw -bordermode ignore 
    place $top.lis41 \
        -in $top -x 70 -y 420 -anchor nw -bordermode ignore 
    place $top.tex42 \
        -in $top -x 350 -y 410 -anchor nw -bordermode ignore 
    place $top.che43 \
        -in $top -x 440 -y 170 -anchor nw -bordermode ignore 
    place $top.rad44 \
        -in $top -x 460 -y 220 -anchor nw -bordermode ignore 
    place $top.sca45 \
        -in $top -x 440 -y 300 -anchor nw -bordermode ignore 
    place $top.spi46 \
        -in $top -x 310 -y 120 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top34

