#! /usr/bin/env python
#
# Generated by PAGE version 4.2
# In conjunction with Tcl version 8.6
#    Jan. 21, 2014 06:35:03 AM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *
try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1



import main_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('Main')
    root.geometry('600x450+918+173')
    w = Main (root)
    main_support.init(root, w)
    root.mainloop()

w = None
def create_Main (root):
    '''Starting point when module is imported by another program.'''
    global w, w_win
    w = Toplevel (root)
    w.title('Main')
    w.geometry('600x450+918+173')
    w_win = Main (w)
    main_support.init(w, w_win)
    return w_win

def destroy_Main ():
    global w
    w.destroy()
    w = None







class Main:
    def __init__(self, master=None):
        _bgcolor = 'wheat'  # X11 color: #f5deb3
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#b2c9f4' # Closest X11 color: 'SlateGray2'
        _ana1color = '#eaf4b2' # Closest X11 color: '{pale goldenrod}'
        _ana2color = '#f4bcb2' # Closest X11 color: 'RosyBrown2'
        font12 = "-family {Nimbus Sans L} -size 20 -weight normal  " + \
            "-slant roman -underline 0 -overstrike 0"
        font13 = "-family {Nimbus Sans L} -size 18 -weight normal  " + \
            "-slant roman -underline 0 -overstrike 0"
        master.configure(background=_bgcolor)
        master.configure(highlightbackground="wheat")
        master.configure(highlightcolor="black")


        self.Button1 = Button (master)
        self.Button1.place(relx=0.3,rely=0.4,height=40,width=260)
        self.Button1.configure(activebackground="#f9f9f9")
        self.Button1.configure(background=_bgcolor)
        self.Button1.configure(command=main_support.advance)
        self.Button1.configure(disabledforeground="#b8a786")
        self.Button1.configure(font=font12)
        self.Button1.configure(highlightbackground="wheat")
        self.Button1.configure(text='''Advance Progress Bar''')

        self.Button2 = Button (master)
        self.Button2.place(relx=0.45,rely=0.67,height=25,width=49)
        self.Button2.configure(activebackground="#f9f9f9")
        self.Button2.configure(background=_bgcolor)
        self.Button2.configure(command=main_support.quit)
        self.Button2.configure(disabledforeground="#b8a786")
        self.Button2.configure(highlightbackground="wheat")
        self.Button2.configure(text='''Quit''')

        self.Label1 = Label (master)
        self.Label1.place(relx=0.23,rely=0.18,height=49,width=352)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(background=_bgcolor)
        self.Label1.configure(disabledforeground="#b8a786")
        self.Label1.configure(font=font13)
        self.Label1.configure(highlightbackground="wheat")
        self.Label1.configure(text='''Example of Using a Progress bar''')







if __name__ == '__main__':
    vp_start_gui()



