#! /usr/bin/env python
#
# Generated by PAGE version 4.2
# In conjunction with Tcl version 8.6
#    Jan. 19, 2014 09:47:50 AM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *
try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1



import progress_bar_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('Progress_Bar')
    root.geometry('301x129+472+154')
    progress_bar_support.set_Tk_var()
    #set_Tk_var()
    w = Progress_Bar (root)
    progress_bar_support.init(root, w)
    root.mainloop()

w = None
def create_Progress_Bar (root):
    '''Starting point when module is imported by another program.'''
    global w, w_win
    w = Toplevel (root)
    w.title('Progress_Bar')
    w.geometry('301x129+472+154')
    progress_bar_support.set_Tk_var()
    w_win = Progress_Bar (w)
    progress_bar_support.init(w, w_win)
    return w_win

def destroy_Progress_Bar ():
    global w
    w.destroy()
    w = None







class Progress_Bar:
    def __init__(self, master=None):
        _bgcolor = 'wheat'  # X11 color: #f5deb3
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#b2c9f4' # Closest X11 color: 'SlateGray2'
        _ana1color = '#eaf4b2' # Closest X11 color: '{pale goldenrod}' 
        _ana2color = '#f4bcb2' # Closest X11 color: 'RosyBrown2' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])
        master.configure(background=_bgcolor)
        master.configure(highlightbackground="wheat")
        master.configure(highlightcolor="black")


        self.TProgressbar1 = ttk.Progressbar (master)
        self.TProgressbar1.place(relx=0.17,rely=0.47,relheight=0.15
                ,relwidth=0.66)
        self.TProgressbar1.configure(variable=progress_bar_support.prog_var)







if __name__ == '__main__':
    vp_start_gui()



