
/* File generated by gen_cfile.py. Should not be modified. */

#include "motor_objdict.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS32 Strain_Gauge1 = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS32 Strain_Gauge2 = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS32 Strain_Gauge3 = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS32 Strain_Gauge4 = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */
UNS8 Voltage_24V = 0x0;		/* Mapped at index 0x4000, subindex 0x00 */
INTEGER32 Position_actual_value = 0x0;		/* Mapped at index 0x6064, subindex 0x00 */
INTEGER32 Velocity_actual_value = 0x0;		/* Mapped at index 0x606C, subindex 0x00 */
INTEGER16 Current_actual_value = 0x0;		/* Mapped at index 0x6078, subindex 0x00 */
INTEGER32 Target_position = 0x0;		/* Mapped at index 0x607A, subindex 0x00 */
INTEGER32 Target_velocity = 0x0;		/* Mapped at index 0x60FF, subindex 0x00 */
UNS16 Motor_data_Continous_current_limit = 0x0;		/* Mapped at index 0x6410, subindex 0x01 */
UNS16 Motor_data_Output_current_limit = 0x0;		/* Mapped at index 0x6410, subindex 0x02 */
UNS8 Motor_data_Pole_pair_number = 0x0;		/* Mapped at index 0x6410, subindex 0x03 */
UNS16 Motor_data_Maximal_speed_in_current_mode = 0x0;		/* Mapped at index 0x6410, subindex 0x04 */
UNS16 Motor_data_Thermal_time_constant_winding = 0x0;		/* Mapped at index 0x6410, subindex 0x05 */
UNS32 Supported_drive_modes = 0x0;		/* Mapped at index 0x6502, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 Motor_Board_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Motor_Board_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Motor_Board_iam_a_slave = 1;

TIMER_HANDLE Motor_Board_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 Motor_Board_obj1000 = 0x0;	/* 0 */
                    subindex Motor_Board_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 Motor_Board_obj1001 = 0x0;	/* 0 */
                    subindex Motor_Board_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 Motor_Board_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t Motor_Board_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex Motor_Board_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 Motor_Board_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 Motor_Board_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 Motor_Board_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 Motor_Board_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 Motor_Board_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 Motor_Board_highestSubIndex_obj1016 = 0;
                    UNS32 Motor_Board_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 Motor_Board_obj1017 = 0x3E8;	/* 1000 */
                    ODCallback_t Motor_Board_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex Motor_Board_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 Motor_Board_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 Motor_Board_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 Motor_Board_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 Motor_Board_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex Motor_Board_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x602;	/* 1538 */
                    UNS32 Motor_Board_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x582;	/* 1410 */
                    subindex Motor_Board_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1400_COB_ID_used_by_PDO = 0x181;	/* 385 */
                    UNS8 Motor_Board_obj1400_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Motor_Board_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex Motor_Board_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1401_COB_ID_used_by_PDO = 0x281;	/* 641 */
                    UNS8 Motor_Board_obj1401_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Motor_Board_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex Motor_Board_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 Motor_Board_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex Motor_Board_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 Motor_Board_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex Motor_Board_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1403_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 Motor_Board_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1600[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Motor_Board_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1600[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1600[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1600[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1600[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1600[7] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 Motor_Board_highestSubIndex_obj1601 = 8; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Motor_Board_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1601[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1601[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1601[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1601[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1601[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1601[7] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 Motor_Board_highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Motor_Board_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1602[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1602[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1602[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1602[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1602[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1602[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1602[7] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 Motor_Board_highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1603[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Motor_Board_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1603[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1603[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1603[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1603[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1603[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1603[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1603[7] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1800_COB_ID_used_by_PDO = 0x182;	/* 386 */
                    UNS8 Motor_Board_obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Motor_Board_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1800_Event_Timer = 0x14;	/* 20 */
                    UNS8 Motor_Board_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Motor_Board_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Motor_Board_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 Motor_Board_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Motor_Board_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Motor_Board_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 Motor_Board_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Motor_Board_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Motor_Board_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 Motor_Board_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Motor_Board_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Motor_Board_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1803_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 Motor_Board_highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1A00[] = 
                    {
                      0x60640020	/* 1617166368 */
                    };
                    subindex Motor_Board_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A00[0] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 Motor_Board_highestSubIndex_obj1A01 = 8; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1A01[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Motor_Board_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A01[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A01[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A01[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A01[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A01[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A01[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A01[7] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 Motor_Board_highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Motor_Board_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A02[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A02[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A02[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A02[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A02[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A02[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A02[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A02[7] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 Motor_Board_highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Motor_Board_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A03[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A03[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A03[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A03[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A03[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A03[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A03[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A03[7] }
                     };

/* index 0x2001 :   Mapped variable Strain_Gauge1 */
                    subindex Motor_Board_Index2001[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Strain_Gauge1 }
                     };

/* index 0x2002 :   Mapped variable Strain_Gauge2 */
                    subindex Motor_Board_Index2002[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Strain_Gauge2 }
                     };

/* index 0x2003 :   Mapped variable Strain_Gauge3 */
                    subindex Motor_Board_Index2003[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Strain_Gauge3 }
                     };

/* index 0x2004 :   Mapped variable Strain_Gauge4 */
                    subindex Motor_Board_Index2004[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Strain_Gauge4 }
                     };

/* index 0x4000 :   Mapped variable Voltage_24V */
                    subindex Motor_Board_Index4000[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Voltage_24V }
                     };

/* index 0x6064 :   Mapped variable Position actual value */
                    subindex Motor_Board_Index6064[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Position_actual_value }
                     };

/* index 0x606C :   Mapped variable Velocity actual value */
                    subindex Motor_Board_Index606C[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Velocity_actual_value }
                     };

/* index 0x6078 :   Mapped variable Current actual value */
                    subindex Motor_Board_Index6078[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&Current_actual_value }
                     };

/* index 0x607A :   Mapped variable Target position */
                    subindex Motor_Board_Index607A[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_position }
                     };

/* index 0x60FF :   Mapped variable Target velocity */
                    subindex Motor_Board_Index60FF[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_velocity }
                     };

/* index 0x6410 :   Mapped variable Motor data */
                    UNS8 Motor_Board_highestSubIndex_obj6410 = 5; /* number of subindex - 1*/
                    subindex Motor_Board_Index6410[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj6410 },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Continous_current_limit },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Output_current_limit },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_data_Pole_pair_number },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Maximal_speed_in_current_mode },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Thermal_time_constant_winding }
                     };

/* index 0x6502 :   Mapped variable Supported drive modes */
                    subindex Motor_Board_Index6502[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Supported_drive_modes }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Motor_Board_objdict[] = 
{
  { (subindex*)Motor_Board_Index1000,sizeof(Motor_Board_Index1000)/sizeof(Motor_Board_Index1000[0]), 0x1000},
  { (subindex*)Motor_Board_Index1001,sizeof(Motor_Board_Index1001)/sizeof(Motor_Board_Index1001[0]), 0x1001},
  { (subindex*)Motor_Board_Index1017,sizeof(Motor_Board_Index1017)/sizeof(Motor_Board_Index1017[0]), 0x1017},
  { (subindex*)Motor_Board_Index1018,sizeof(Motor_Board_Index1018)/sizeof(Motor_Board_Index1018[0]), 0x1018},
  { (subindex*)Motor_Board_Index1200,sizeof(Motor_Board_Index1200)/sizeof(Motor_Board_Index1200[0]), 0x1200},
  { (subindex*)Motor_Board_Index1400,sizeof(Motor_Board_Index1400)/sizeof(Motor_Board_Index1400[0]), 0x1400},
  { (subindex*)Motor_Board_Index1401,sizeof(Motor_Board_Index1401)/sizeof(Motor_Board_Index1401[0]), 0x1401},
  { (subindex*)Motor_Board_Index1402,sizeof(Motor_Board_Index1402)/sizeof(Motor_Board_Index1402[0]), 0x1402},
  { (subindex*)Motor_Board_Index1403,sizeof(Motor_Board_Index1403)/sizeof(Motor_Board_Index1403[0]), 0x1403},
  { (subindex*)Motor_Board_Index1600,sizeof(Motor_Board_Index1600)/sizeof(Motor_Board_Index1600[0]), 0x1600},
  { (subindex*)Motor_Board_Index1601,sizeof(Motor_Board_Index1601)/sizeof(Motor_Board_Index1601[0]), 0x1601},
  { (subindex*)Motor_Board_Index1602,sizeof(Motor_Board_Index1602)/sizeof(Motor_Board_Index1602[0]), 0x1602},
  { (subindex*)Motor_Board_Index1603,sizeof(Motor_Board_Index1603)/sizeof(Motor_Board_Index1603[0]), 0x1603},
  { (subindex*)Motor_Board_Index1800,sizeof(Motor_Board_Index1800)/sizeof(Motor_Board_Index1800[0]), 0x1800},
  { (subindex*)Motor_Board_Index1801,sizeof(Motor_Board_Index1801)/sizeof(Motor_Board_Index1801[0]), 0x1801},
  { (subindex*)Motor_Board_Index1802,sizeof(Motor_Board_Index1802)/sizeof(Motor_Board_Index1802[0]), 0x1802},
  { (subindex*)Motor_Board_Index1803,sizeof(Motor_Board_Index1803)/sizeof(Motor_Board_Index1803[0]), 0x1803},
  { (subindex*)Motor_Board_Index1A00,sizeof(Motor_Board_Index1A00)/sizeof(Motor_Board_Index1A00[0]), 0x1A00},
  { (subindex*)Motor_Board_Index1A01,sizeof(Motor_Board_Index1A01)/sizeof(Motor_Board_Index1A01[0]), 0x1A01},
  { (subindex*)Motor_Board_Index1A02,sizeof(Motor_Board_Index1A02)/sizeof(Motor_Board_Index1A02[0]), 0x1A02},
  { (subindex*)Motor_Board_Index1A03,sizeof(Motor_Board_Index1A03)/sizeof(Motor_Board_Index1A03[0]), 0x1A03},
  { (subindex*)Motor_Board_Index2001,sizeof(Motor_Board_Index2001)/sizeof(Motor_Board_Index2001[0]), 0x2001},
  { (subindex*)Motor_Board_Index2002,sizeof(Motor_Board_Index2002)/sizeof(Motor_Board_Index2002[0]), 0x2002},
  { (subindex*)Motor_Board_Index2003,sizeof(Motor_Board_Index2003)/sizeof(Motor_Board_Index2003[0]), 0x2003},
  { (subindex*)Motor_Board_Index2004,sizeof(Motor_Board_Index2004)/sizeof(Motor_Board_Index2004[0]), 0x2004},
  { (subindex*)Motor_Board_Index4000,sizeof(Motor_Board_Index4000)/sizeof(Motor_Board_Index4000[0]), 0x4000},
  { (subindex*)Motor_Board_Index6064,sizeof(Motor_Board_Index6064)/sizeof(Motor_Board_Index6064[0]), 0x6064},
  { (subindex*)Motor_Board_Index606C,sizeof(Motor_Board_Index606C)/sizeof(Motor_Board_Index606C[0]), 0x606C},
  { (subindex*)Motor_Board_Index6078,sizeof(Motor_Board_Index6078)/sizeof(Motor_Board_Index6078[0]), 0x6078},
  { (subindex*)Motor_Board_Index607A,sizeof(Motor_Board_Index607A)/sizeof(Motor_Board_Index607A[0]), 0x607A},
  { (subindex*)Motor_Board_Index60FF,sizeof(Motor_Board_Index60FF)/sizeof(Motor_Board_Index60FF[0]), 0x60FF},
  { (subindex*)Motor_Board_Index6410,sizeof(Motor_Board_Index6410)/sizeof(Motor_Board_Index6410[0]), 0x6410},
  { (subindex*)Motor_Board_Index6502,sizeof(Motor_Board_Index6502)/sizeof(Motor_Board_Index6502[0]), 0x6502},
};

const indextable * Motor_Board_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1017: i = 2;*callbacks = Motor_Board_Index1017_callbacks; break;
		case 0x1018: i = 3;break;
		case 0x1200: i = 4;break;
		case 0x1400: i = 5;break;
		case 0x1401: i = 6;break;
		case 0x1402: i = 7;break;
		case 0x1403: i = 8;break;
		case 0x1600: i = 9;break;
		case 0x1601: i = 10;break;
		case 0x1602: i = 11;break;
		case 0x1603: i = 12;break;
		case 0x1800: i = 13;*callbacks = Motor_Board_Index1800_callbacks; break;
		case 0x1801: i = 14;*callbacks = Motor_Board_Index1801_callbacks; break;
		case 0x1802: i = 15;*callbacks = Motor_Board_Index1802_callbacks; break;
		case 0x1803: i = 16;*callbacks = Motor_Board_Index1803_callbacks; break;
		case 0x1A00: i = 17;break;
		case 0x1A01: i = 18;break;
		case 0x1A02: i = 19;break;
		case 0x1A03: i = 20;break;
		case 0x2001: i = 21;break;
		case 0x2002: i = 22;break;
		case 0x2003: i = 23;break;
		case 0x2004: i = 24;break;
		case 0x4000: i = 25;break;
		case 0x6064: i = 26;break;
		case 0x606C: i = 27;break;
		case 0x6078: i = 28;break;
		case 0x607A: i = 29;break;
		case 0x60FF: i = 30;break;
		case 0x6410: i = 31;break;
		case 0x6502: i = 32;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &Motor_Board_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Motor_Board_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index Motor_Board_firstIndex = {
  4, /* SDO_SVR */
  0, /* SDO_CLT */
  5, /* PDO_RCV */
  9, /* PDO_RCV_MAP */
  13, /* PDO_TRS */
  17 /* PDO_TRS_MAP */
};

const quick_index Motor_Board_lastIndex = {
  4, /* SDO_SVR */
  0, /* SDO_CLT */
  8, /* PDO_RCV */
  12, /* PDO_RCV_MAP */
  16, /* PDO_TRS */
  20 /* PDO_TRS_MAP */
};

const UNS16 Motor_Board_ObjdictSize = sizeof(Motor_Board_objdict)/sizeof(Motor_Board_objdict[0]); 

CO_Data Motor_Board_Data = CANOPEN_NODE_DATA_INITIALIZER(Motor_Board);

