
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MOTOR_OBJDICT_H
#define MOTOR_OBJDICT_H

#include "../canFestival/include/data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Motor_Board_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Motor_Board_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data Motor_Board_Data;
extern INTEGER32 Strain_Gauge1;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS32 Strain_Gauge2;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS32 Strain_Gauge3;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS32 Strain_Gauge4;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS32 Target_Tension;		/* Mapped at index 0x3000, subindex 0x00*/
extern INTEGER32 Actual_Position;		/* Mapped at index 0x3001, subindex 0x00*/
extern INTEGER32 Actual_Velocity;		/* Mapped at index 0x3002, subindex 0x00*/
extern UNS32 Target_Position;		/* Mapped at index 0x3003, subindex 0x00*/
extern UNS32 Target_Velocity;		/* Mapped at index 0x3004, subindex 0x00*/
extern INTEGER32 Commanded_Current;		/* Mapped at index 0x3005, subindex 0x00*/
extern UNS8 Voltage_24V;		/* Mapped at index 0x4000, subindex 0x00*/

#endif // MOTOR_OBJDICT_H
