
/* File generated by gen_cfile.py. Should not be modified. */

#include "motor_objdict_72.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
INTEGER32 sensor71_strain_gauge_processed_Strain_Gauge_1P = 0x0;		/* Mapped at index 0x2010, subindex 0x01 */
INTEGER32 sensor71_strain_gauge_processed_Strain_Gauge_2P = 0x0;		/* Mapped at index 0x2010, subindex 0x02 */
INTEGER32 sensor71_strain_gauge_processed_Strain_Gauge_3P = 0x0;		/* Mapped at index 0x2010, subindex 0x03 */
INTEGER32 sensor71_strain_gauge_processed_Strain_Gauge_4P = 0x0;		/* Mapped at index 0x2010, subindex 0x04 */
INTEGER32 sensor71_strain_gauge_processed_Strain_Gauge_5P = 0x0;		/* Mapped at index 0x2010, subindex 0x05 */
INTEGER32 sensor71_strain_gauge_processed_Strain_Gauge_6P = 0x0;		/* Mapped at index 0x2010, subindex 0x06 */
INTEGER32 sensor71_strain_gauge_processed_Strain_Gauge_7P = 0x0;		/* Mapped at index 0x2010, subindex 0x07 */
INTEGER32 sensor71_strain_gauge_processed_Strain_Gauge_8P = 0x0;		/* Mapped at index 0x2010, subindex 0x08 */
INTEGER32 sensor71_strain_gauge_raw_Strain_Gauge_1R = 0x0;		/* Mapped at index 0x2011, subindex 0x01 */
INTEGER32 sensor71_strain_gauge_raw_Strain_Gauge_2R = 0x0;		/* Mapped at index 0x2011, subindex 0x02 */
INTEGER32 sensor71_strain_gauge_raw_Strain_Gauge_3R = 0x0;		/* Mapped at index 0x2011, subindex 0x03 */
INTEGER32 sensor71_strain_gauge_raw_Strain_Gauge_4R = 0x0;		/* Mapped at index 0x2011, subindex 0x04 */
INTEGER32 sensor71_strain_gauge_raw_Strain_Gauge_5R = 0x0;		/* Mapped at index 0x2011, subindex 0x05 */
INTEGER32 sensor71_strain_gauge_raw_Strain_Gauge_6R = 0x0;		/* Mapped at index 0x2011, subindex 0x06 */
INTEGER32 sensor71_strain_gauge_raw_Strain_Gauge_7R = 0x0;		/* Mapped at index 0x2011, subindex 0x07 */
INTEGER32 sensor71_strain_gauge_raw_Strain_Gauge_8R = 0x0;		/* Mapped at index 0x2011, subindex 0x08 */
UNS8 motor72_configuration_Current_Control_Type = 0x0;		/* Mapped at index 0x2020, subindex 0x01 */
UNS32 motor72_configuration_Main_Loop_Update_Frequency = 0x0;		/* Mapped at index 0x2020, subindex 0x02 */
UNS32 motor72_configuration_PWM_Frequency = 0x0;		/* Mapped at index 0x2020, subindex 0x03 */
UNS32 motor72_configuration_Gear_Ratio_1000 = 0x0;		/* Mapped at index 0x2020, subindex 0x04 */
INTEGER32 motor72_state_Current_Postition = 0x0;		/* Mapped at index 0x2021, subindex 0x01 */
INTEGER32 motor72_state_Current_Velocity = 0x0;		/* Mapped at index 0x2021, subindex 0x02 */
INTEGER32 motor72_state_Current_Torque = 0x0;		/* Mapped at index 0x2021, subindex 0x03 */
INTEGER32 motor72_state_Current_Motor_Voltage = 0x0;		/* Mapped at index 0x2021, subindex 0x04 */
INTEGER32 motor72_state_Current_Motor_Current = 0x0;		/* Mapped at index 0x2021, subindex 0x05 */
UNS8 motor72_state_Undefined = 0x0;		/* Mapped at index 0x2021, subindex 0x06 */
UNS8 motor72_state_Undefined = 0x0;		/* Mapped at index 0x2021, subindex 0x07 */
UNS8 motor72_state_Undefined = 0x0;		/* Mapped at index 0x2021, subindex 0x08 */
INTEGER32 motor72_postition_control_Commanded_Position = 0x0;		/* Mapped at index 0x2022, subindex 0x01 */
UNS16 motor72_postition_control_P_Gain = 0x0;		/* Mapped at index 0x2022, subindex 0x02 */
UNS16 motor72_postition_control_I_Gain = 0x0;		/* Mapped at index 0x2022, subindex 0x03 */
UNS16 motor72_postition_control_D_Gain = 0x0;		/* Mapped at index 0x2022, subindex 0x04 */
REAL32 motor72_postition_control_SS_Gain_1st_Order = 0.000000;		/* Mapped at index 0x2022, subindex 0x05 */
REAL32 motor72_postition_control_SS_Gain_2nd_Order = 0.000000;		/* Mapped at index 0x2022, subindex 0x06 */
REAL32 motor72_postition_control_SS_Gain_3rd_Order = 0.000000;		/* Mapped at index 0x2022, subindex 0x07 */
REAL32 motor72_postition_control_O_Gain_1st_Order = 0.000000;		/* Mapped at index 0x2022, subindex 0x08 */
REAL32 motor72_postition_control_O_Gain_2nd_Order = 0.000000;		/* Mapped at index 0x2022, subindex 0x09 */
REAL32 motor72_postition_control_O_Gain_3rd_Order = 0.000000;		/* Mapped at index 0x2022, subindex 0x0A */
INTEGER32 motor72_velocity_control_Commanded_Velocity = 0x0;		/* Mapped at index 0x2023, subindex 0x01 */
UNS16 motor72_velocity_control_P_Gain = 0x0;		/* Mapped at index 0x2023, subindex 0x02 */
UNS16 motor72_velocity_control_I_Gain = 0x0;		/* Mapped at index 0x2023, subindex 0x03 */
UNS16 motor72_velocity_control_D_Gain = 0x0;		/* Mapped at index 0x2023, subindex 0x04 */
REAL32 motor72_velocity_control_SS_Gain_1st_Order = 0.000000;		/* Mapped at index 0x2023, subindex 0x05 */
REAL32 motor72_velocity_control_SS_Gain_2nd_Order = 0.000000;		/* Mapped at index 0x2023, subindex 0x06 */
REAL32 motor72_velocity_control_SS_Gain_3rd_Order = 0.000000;		/* Mapped at index 0x2023, subindex 0x07 */
REAL32 motor72_velocity_control_O_Gain_1st_Order = 0.000000;		/* Mapped at index 0x2023, subindex 0x08 */
REAL32 motor72_velocity_control_O_Gain_2nd_Order = 0.000000;		/* Mapped at index 0x2023, subindex 0x09 */
REAL32 motor72_velocity_control_O_Gain_3rd_Order = 0.000000;		/* Mapped at index 0x2023, subindex 0x0A */
INTEGER32 motor72_torque_control_Commanded_Torque = 0x0;		/* Mapped at index 0x2024, subindex 0x01 */
UNS16 motor72_torque_control_P_Gain = 0x0;		/* Mapped at index 0x2024, subindex 0x02 */
UNS16 motor72_torque_control_I_Gain = 0x0;		/* Mapped at index 0x2024, subindex 0x03 */
UNS16 motor72_torque_control_D_Gain = 0x0;		/* Mapped at index 0x2024, subindex 0x04 */
REAL32 motor72_torque_control_SS_Gain_1st_Order = 0.000000;		/* Mapped at index 0x2024, subindex 0x05 */
REAL32 motor72_torque_control_SS_Gain_2nd_Order = 0.000000;		/* Mapped at index 0x2024, subindex 0x06 */
REAL32 motor72_torque_control_SS_Gain_3rd_Order = 0.000000;		/* Mapped at index 0x2024, subindex 0x07 */
REAL32 motor72_torque_control_O_Gain_1st_Order = 0.000000;		/* Mapped at index 0x2024, subindex 0x08 */
REAL64 motor72_torque_control_O_Gain_2nd_Order = 0.000000;		/* Mapped at index 0x2024, subindex 0x09 */
REAL32 motor72_torque_control_O_Gain_3rd_Order = 0.000000;		/* Mapped at index 0x2024, subindex 0x0A */
UNS8 motor72_impedance_control_Commanded_Torque = 0x0;		/* Mapped at index 0x2025, subindex 0x01 */
UNS8 motor72_impedance_control_Actual_Length = 0x0;		/* Mapped at index 0x2025, subindex 0x02 */
UNS8 motor72_impedance_control_Actual_Velocity = 0x0;		/* Mapped at index 0x2025, subindex 0x03 */
UNS8 motor72_impedance_control_Length_Offset = 0x0;		/* Mapped at index 0x2025, subindex 0x04 */
UNS8 motor72_impedance_control_Velocity_Offset = 0x0;		/* Mapped at index 0x2025, subindex 0x05 */
UNS8 motor72_impedance_control_Tension_Offset = 0x0;		/* Mapped at index 0x2025, subindex 0x06 */
UNS8 motor72_impedance_control_Velocity_Gain = 0x0;		/* Mapped at index 0x2025, subindex 0x07 */
UNS8 motor72_impedance_control_ = 0x0;		/* Mapped at index 0x2025, subindex 0x08 */
UNS8 motor72_impedance_control_Undefined = 0x0;		/* Mapped at index 0x2025, subindex 0x09 */
UNS8 motor72_impedance_control_Undefined = 0x0;		/* Mapped at index 0x2025, subindex 0x0A */
UNS8 motor72_impedance_control_Undefined = 0x0;		/* Mapped at index 0x2025, subindex 0x0B */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 Motor_Board_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Motor_Board_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Motor_Board_iam_a_slave = 1;

TIMER_HANDLE Motor_Board_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 Motor_Board_obj1000 = 0x0;	/* 0 */
                    subindex Motor_Board_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 Motor_Board_obj1001 = 0x0;	/* 0 */
                    subindex Motor_Board_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 Motor_Board_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t Motor_Board_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex Motor_Board_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 Motor_Board_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 Motor_Board_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 Motor_Board_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 Motor_Board_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 Motor_Board_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 Motor_Board_highestSubIndex_obj1016 = 0;
                    UNS32 Motor_Board_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 Motor_Board_obj1017 = 0xA;	/* 10 */
                    ODCallback_t Motor_Board_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex Motor_Board_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 Motor_Board_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 Motor_Board_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 Motor_Board_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 Motor_Board_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex Motor_Board_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x602;	/* 1538 */
                    UNS32 Motor_Board_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x582;	/* 1410 */
                    subindex Motor_Board_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 Motor_Board_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 Motor_Board_obj1280_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex Motor_Board_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x603;	/* 1539 */
                    UNS32 Motor_Board_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x583;	/* 1411 */
                    UNS8 Motor_Board_obj1281_Node_ID_of_the_SDO_Server = 0x3;	/* 3 */
                    subindex Motor_Board_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1281 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1281_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1281_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1281_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1282 :   Client SDO 3 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1282 = 3; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1282_COB_ID_Client_to_Server_Transmit_SDO = 0x604;	/* 1540 */
                    UNS32 Motor_Board_obj1282_COB_ID_Server_to_Client_Receive_SDO = 0x584;	/* 1412 */
                    UNS8 Motor_Board_obj1282_Node_ID_of_the_SDO_Server = 0x4;	/* 4 */
                    subindex Motor_Board_Index1282[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1282 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1282_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1282_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1282_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1283 :   Client SDO 4 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1283 = 3; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1283_COB_ID_Client_to_Server_Transmit_SDO = 0x671;	/* 1649 */
                    UNS32 Motor_Board_obj1283_COB_ID_Server_to_Client_Receive_SDO = 0x651;	/* 1617 */
                    UNS8 Motor_Board_obj1283_Node_ID_of_the_SDO_Server = 0x71;	/* 113 */
                    subindex Motor_Board_Index1283[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1283 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1283_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1283_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1283_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1284 :   Client SDO 5 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1284 = 3; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1284_COB_ID_Client_to_Server_Transmit_SDO = 0x672;	/* 1650 */
                    UNS32 Motor_Board_obj1284_COB_ID_Server_to_Client_Receive_SDO = 0x652;	/* 1618 */
                    UNS8 Motor_Board_obj1284_Node_ID_of_the_SDO_Server = 0x72;	/* 114 */
                    subindex Motor_Board_Index1284[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1284 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1284_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1284_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1284_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1285 :   Client SDO 6 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1285 = 3; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1285_COB_ID_Client_to_Server_Transmit_SDO = 0x673;	/* 1651 */
                    UNS32 Motor_Board_obj1285_COB_ID_Server_to_Client_Receive_SDO = 0x653;	/* 1619 */
                    UNS8 Motor_Board_obj1285_Node_ID_of_the_SDO_Server = 0x73;	/* 115 */
                    subindex Motor_Board_Index1285[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1285 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1285_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1285_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1285_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1400_COB_ID_used_by_PDO = 0x171;	/* 369 */
                    UNS8 Motor_Board_obj1400_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Motor_Board_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex Motor_Board_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1401_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1401_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Motor_Board_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex Motor_Board_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1402_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1402_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Motor_Board_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex Motor_Board_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1403_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1403_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Motor_Board_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex Motor_Board_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1403_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 Motor_Board_highestSubIndex_obj1600 = 2; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1600[] = 
                    {
                      0x20100120,	/* 537919776 */
                      0x20110120	/* 537985312 */
                    };
                    subindex Motor_Board_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1600[1] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 Motor_Board_highestSubIndex_obj1601 = 2; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Motor_Board_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1601[1] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 Motor_Board_highestSubIndex_obj1602 = 2; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    ODCallback_t Motor_Board_Index1602_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Motor_Board_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1602[1] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 Motor_Board_highestSubIndex_obj1603 = 2; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1603[] = 
                    {
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Motor_Board_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1603[1] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1800_COB_ID_used_by_PDO = 0x271;	/* 625 */
                    UNS8 Motor_Board_obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Motor_Board_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1800_Event_Timer = 0x1;	/* 1 */
                    UNS8 Motor_Board_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Motor_Board_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Motor_Board_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1801_COB_ID_used_by_PDO = 0x272;	/* 626 */
                    UNS8 Motor_Board_obj1801_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Motor_Board_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1801_Event_Timer = 0x1;	/* 1 */
                    UNS8 Motor_Board_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Motor_Board_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Motor_Board_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1802_COB_ID_used_by_PDO = 0x273;	/* 627 */
                    UNS8 Motor_Board_obj1802_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Motor_Board_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Motor_Board_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Motor_Board_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 Motor_Board_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1803_COB_ID_used_by_PDO = 0x274;	/* 628 */
                    UNS8 Motor_Board_obj1803_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Motor_Board_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_Board_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 Motor_Board_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t Motor_Board_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Motor_Board_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Board_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_obj1803_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 Motor_Board_highestSubIndex_obj1A00 = 2; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1A00[] = 
                    {
                      0x20210120,	/* 539033888 */
                      0x20210220	/* 539034144 */
                    };
                    subindex Motor_Board_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A00[1] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 Motor_Board_highestSubIndex_obj1A01 = 1; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1A01[] = 
                    {
                      0x20210320	/* 539034400 */
                    };
                    subindex Motor_Board_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A01[0] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 Motor_Board_highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Motor_Board_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A02[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A02[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A02[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A02[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A02[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A02[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A02[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A02[7] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 Motor_Board_highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    UNS32 Motor_Board_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex Motor_Board_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A03[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A03[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A03[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A03[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A03[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A03[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A03[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_Board_obj1A03[7] }
                     };

/* index 0x2010 :   Mapped variable sensor71_strain_gauge_processed */
                    UNS8 Motor_Board_highestSubIndex_obj2010 = 8; /* number of subindex - 1*/
                    subindex Motor_Board_Index2010[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj2010 },
                       { RW, int32, sizeof (INTEGER32), (void*)&sensor71_strain_gauge_processed_Strain_Gauge_1P },
                       { RW, int32, sizeof (INTEGER32), (void*)&sensor71_strain_gauge_processed_Strain_Gauge_2P },
                       { RW, int32, sizeof (INTEGER32), (void*)&sensor71_strain_gauge_processed_Strain_Gauge_3P },
                       { RW, int32, sizeof (INTEGER32), (void*)&sensor71_strain_gauge_processed_Strain_Gauge_4P },
                       { RW, int32, sizeof (INTEGER32), (void*)&sensor71_strain_gauge_processed_Strain_Gauge_5P },
                       { RW, int32, sizeof (INTEGER32), (void*)&sensor71_strain_gauge_processed_Strain_Gauge_6P },
                       { RW, int32, sizeof (INTEGER32), (void*)&sensor71_strain_gauge_processed_Strain_Gauge_7P },
                       { RW, int32, sizeof (INTEGER32), (void*)&sensor71_strain_gauge_processed_Strain_Gauge_8P }
                     };

/* index 0x2011 :   Mapped variable sensor71_strain_gauge_raw */
                    UNS8 Motor_Board_highestSubIndex_obj2011 = 8; /* number of subindex - 1*/
                    subindex Motor_Board_Index2011[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj2011 },
                       { RW, int32, sizeof (INTEGER32), (void*)&sensor71_strain_gauge_raw_Strain_Gauge_1R },
                       { RW, int32, sizeof (INTEGER32), (void*)&sensor71_strain_gauge_raw_Strain_Gauge_2R },
                       { RW, int32, sizeof (INTEGER32), (void*)&sensor71_strain_gauge_raw_Strain_Gauge_3R },
                       { RW, int32, sizeof (INTEGER32), (void*)&sensor71_strain_gauge_raw_Strain_Gauge_4R },
                       { RW, int32, sizeof (INTEGER32), (void*)&sensor71_strain_gauge_raw_Strain_Gauge_5R },
                       { RW, int32, sizeof (INTEGER32), (void*)&sensor71_strain_gauge_raw_Strain_Gauge_6R },
                       { RW, int32, sizeof (INTEGER32), (void*)&sensor71_strain_gauge_raw_Strain_Gauge_7R },
                       { RW, int32, sizeof (INTEGER32), (void*)&sensor71_strain_gauge_raw_Strain_Gauge_8R }
                     };

/* index 0x2020 :   Mapped variable motor72_configuration */
                    UNS8 Motor_Board_highestSubIndex_obj2020 = 4; /* number of subindex - 1*/
                    subindex Motor_Board_Index2020[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj2020 },
                       { RW, uint8, sizeof (UNS8), (void*)&motor72_configuration_Current_Control_Type },
                       { RW, uint32, sizeof (UNS32), (void*)&motor72_configuration_Main_Loop_Update_Frequency },
                       { RW, uint32, sizeof (UNS32), (void*)&motor72_configuration_PWM_Frequency },
                       { RW, uint32, sizeof (UNS32), (void*)&motor72_configuration_Gear_Ratio_1000 }
                     };

/* index 0x2021 :   Mapped variable motor72_state */
                    UNS8 Motor_Board_highestSubIndex_obj2021 = 8; /* number of subindex - 1*/
                    subindex Motor_Board_Index2021[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj2021 },
                       { RW, int32, sizeof (INTEGER32), (void*)&motor72_state_Current_Postition },
                       { RW, int32, sizeof (INTEGER32), (void*)&motor72_state_Current_Velocity },
                       { RW, int32, sizeof (INTEGER32), (void*)&motor72_state_Current_Torque },
                       { RW, int32, sizeof (INTEGER32), (void*)&motor72_state_Current_Motor_Voltage },
                       { RW, int32, sizeof (INTEGER32), (void*)&motor72_state_Current_Motor_Current },
                       { RW, uint8, sizeof (UNS8), (void*)&motor72_state_Undefined },
                       { RW, uint8, sizeof (UNS8), (void*)&motor72_state_Undefined },
                       { RW, uint8, sizeof (UNS8), (void*)&motor72_state_Undefined }
                     };

/* index 0x2022 :   Mapped variable motor72_postition_control */
                    UNS8 Motor_Board_highestSubIndex_obj2022 = 10; /* number of subindex - 1*/
                    subindex Motor_Board_Index2022[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj2022 },
                       { RW, int32, sizeof (INTEGER32), (void*)&motor72_postition_control_Commanded_Position },
                       { RW, uint16, sizeof (UNS16), (void*)&motor72_postition_control_P_Gain },
                       { RW, uint16, sizeof (UNS16), (void*)&motor72_postition_control_I_Gain },
                       { RW, uint16, sizeof (UNS16), (void*)&motor72_postition_control_D_Gain },
                       { RW, real32, sizeof (REAL32), (void*)&motor72_postition_control_SS_Gain_1st_Order },
                       { RW, real32, sizeof (REAL32), (void*)&motor72_postition_control_SS_Gain_2nd_Order },
                       { RW, real32, sizeof (REAL32), (void*)&motor72_postition_control_SS_Gain_3rd_Order },
                       { RW, real32, sizeof (REAL32), (void*)&motor72_postition_control_O_Gain_1st_Order },
                       { RW, real32, sizeof (REAL32), (void*)&motor72_postition_control_O_Gain_2nd_Order },
                       { RW, real32, sizeof (REAL32), (void*)&motor72_postition_control_O_Gain_3rd_Order }
                     };

/* index 0x2023 :   Mapped variable motor72_velocity_control */
                    UNS8 Motor_Board_highestSubIndex_obj2023 = 10; /* number of subindex - 1*/
                    subindex Motor_Board_Index2023[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj2023 },
                       { RW, int32, sizeof (INTEGER32), (void*)&motor72_velocity_control_Commanded_Velocity },
                       { RW, uint16, sizeof (UNS16), (void*)&motor72_velocity_control_P_Gain },
                       { RW, uint16, sizeof (UNS16), (void*)&motor72_velocity_control_I_Gain },
                       { RW, uint16, sizeof (UNS16), (void*)&motor72_velocity_control_D_Gain },
                       { RW, real32, sizeof (REAL32), (void*)&motor72_velocity_control_SS_Gain_1st_Order },
                       { RW, real32, sizeof (REAL32), (void*)&motor72_velocity_control_SS_Gain_2nd_Order },
                       { RW, real32, sizeof (REAL32), (void*)&motor72_velocity_control_SS_Gain_3rd_Order },
                       { RW, real32, sizeof (REAL32), (void*)&motor72_velocity_control_O_Gain_1st_Order },
                       { RW, real32, sizeof (REAL32), (void*)&motor72_velocity_control_O_Gain_2nd_Order },
                       { RW, real32, sizeof (REAL32), (void*)&motor72_velocity_control_O_Gain_3rd_Order }
                     };

/* index 0x2024 :   Mapped variable motor72_torque_control */
                    UNS8 Motor_Board_highestSubIndex_obj2024 = 10; /* number of subindex - 1*/
                    subindex Motor_Board_Index2024[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj2024 },
                       { RW, int32, sizeof (INTEGER32), (void*)&motor72_torque_control_Commanded_Torque },
                       { RW, uint16, sizeof (UNS16), (void*)&motor72_torque_control_P_Gain },
                       { RW, uint16, sizeof (UNS16), (void*)&motor72_torque_control_I_Gain },
                       { RW, uint16, sizeof (UNS16), (void*)&motor72_torque_control_D_Gain },
                       { RW, real32, sizeof (REAL32), (void*)&motor72_torque_control_SS_Gain_1st_Order },
                       { RW, real32, sizeof (REAL32), (void*)&motor72_torque_control_SS_Gain_2nd_Order },
                       { RW, real32, sizeof (REAL32), (void*)&motor72_torque_control_SS_Gain_3rd_Order },
                       { RW, real32, sizeof (REAL32), (void*)&motor72_torque_control_O_Gain_1st_Order },
                       { RW, real64, sizeof (REAL64), (void*)&motor72_torque_control_O_Gain_2nd_Order },
                       { RW, real32, sizeof (REAL32), (void*)&motor72_torque_control_O_Gain_3rd_Order }
                     };

/* index 0x2025 :   Mapped variable motor72_impedance_control */
                    UNS8 Motor_Board_highestSubIndex_obj2025 = 11; /* number of subindex - 1*/
                    subindex Motor_Board_Index2025[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_Board_highestSubIndex_obj2025 },
                       { RW, uint8, sizeof (UNS8), (void*)&motor72_impedance_control_Commanded_Torque },
                       { RW, uint8, sizeof (UNS8), (void*)&motor72_impedance_control_Actual_Length },
                       { RW, uint8, sizeof (UNS8), (void*)&motor72_impedance_control_Actual_Velocity },
                       { RW, uint8, sizeof (UNS8), (void*)&motor72_impedance_control_Length_Offset },
                       { RW, uint8, sizeof (UNS8), (void*)&motor72_impedance_control_Velocity_Offset },
                       { RW, uint8, sizeof (UNS8), (void*)&motor72_impedance_control_Tension_Offset },
                       { RW, uint8, sizeof (UNS8), (void*)&motor72_impedance_control_Velocity_Gain },
                       { RW, uint8, sizeof (UNS8), (void*)&motor72_impedance_control_ },
                       { RW, uint8, sizeof (UNS8), (void*)&motor72_impedance_control_Undefined },
                       { RW, uint8, sizeof (UNS8), (void*)&motor72_impedance_control_Undefined },
                       { RW, uint8, sizeof (UNS8), (void*)&motor72_impedance_control_Undefined }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Motor_Board_objdict[] = 
{
  { (subindex*)Motor_Board_Index1000,sizeof(Motor_Board_Index1000)/sizeof(Motor_Board_Index1000[0]), 0x1000},
  { (subindex*)Motor_Board_Index1001,sizeof(Motor_Board_Index1001)/sizeof(Motor_Board_Index1001[0]), 0x1001},
  { (subindex*)Motor_Board_Index1017,sizeof(Motor_Board_Index1017)/sizeof(Motor_Board_Index1017[0]), 0x1017},
  { (subindex*)Motor_Board_Index1018,sizeof(Motor_Board_Index1018)/sizeof(Motor_Board_Index1018[0]), 0x1018},
  { (subindex*)Motor_Board_Index1200,sizeof(Motor_Board_Index1200)/sizeof(Motor_Board_Index1200[0]), 0x1200},
  { (subindex*)Motor_Board_Index1280,sizeof(Motor_Board_Index1280)/sizeof(Motor_Board_Index1280[0]), 0x1280},
  { (subindex*)Motor_Board_Index1281,sizeof(Motor_Board_Index1281)/sizeof(Motor_Board_Index1281[0]), 0x1281},
  { (subindex*)Motor_Board_Index1282,sizeof(Motor_Board_Index1282)/sizeof(Motor_Board_Index1282[0]), 0x1282},
  { (subindex*)Motor_Board_Index1283,sizeof(Motor_Board_Index1283)/sizeof(Motor_Board_Index1283[0]), 0x1283},
  { (subindex*)Motor_Board_Index1284,sizeof(Motor_Board_Index1284)/sizeof(Motor_Board_Index1284[0]), 0x1284},
  { (subindex*)Motor_Board_Index1285,sizeof(Motor_Board_Index1285)/sizeof(Motor_Board_Index1285[0]), 0x1285},
  { (subindex*)Motor_Board_Index1400,sizeof(Motor_Board_Index1400)/sizeof(Motor_Board_Index1400[0]), 0x1400},
  { (subindex*)Motor_Board_Index1401,sizeof(Motor_Board_Index1401)/sizeof(Motor_Board_Index1401[0]), 0x1401},
  { (subindex*)Motor_Board_Index1402,sizeof(Motor_Board_Index1402)/sizeof(Motor_Board_Index1402[0]), 0x1402},
  { (subindex*)Motor_Board_Index1403,sizeof(Motor_Board_Index1403)/sizeof(Motor_Board_Index1403[0]), 0x1403},
  { (subindex*)Motor_Board_Index1600,sizeof(Motor_Board_Index1600)/sizeof(Motor_Board_Index1600[0]), 0x1600},
  { (subindex*)Motor_Board_Index1601,sizeof(Motor_Board_Index1601)/sizeof(Motor_Board_Index1601[0]), 0x1601},
  { (subindex*)Motor_Board_Index1602,sizeof(Motor_Board_Index1602)/sizeof(Motor_Board_Index1602[0]), 0x1602},
  { (subindex*)Motor_Board_Index1603,sizeof(Motor_Board_Index1603)/sizeof(Motor_Board_Index1603[0]), 0x1603},
  { (subindex*)Motor_Board_Index1800,sizeof(Motor_Board_Index1800)/sizeof(Motor_Board_Index1800[0]), 0x1800},
  { (subindex*)Motor_Board_Index1801,sizeof(Motor_Board_Index1801)/sizeof(Motor_Board_Index1801[0]), 0x1801},
  { (subindex*)Motor_Board_Index1802,sizeof(Motor_Board_Index1802)/sizeof(Motor_Board_Index1802[0]), 0x1802},
  { (subindex*)Motor_Board_Index1803,sizeof(Motor_Board_Index1803)/sizeof(Motor_Board_Index1803[0]), 0x1803},
  { (subindex*)Motor_Board_Index1A00,sizeof(Motor_Board_Index1A00)/sizeof(Motor_Board_Index1A00[0]), 0x1A00},
  { (subindex*)Motor_Board_Index1A01,sizeof(Motor_Board_Index1A01)/sizeof(Motor_Board_Index1A01[0]), 0x1A01},
  { (subindex*)Motor_Board_Index1A02,sizeof(Motor_Board_Index1A02)/sizeof(Motor_Board_Index1A02[0]), 0x1A02},
  { (subindex*)Motor_Board_Index1A03,sizeof(Motor_Board_Index1A03)/sizeof(Motor_Board_Index1A03[0]), 0x1A03},
  { (subindex*)Motor_Board_Index2010,sizeof(Motor_Board_Index2010)/sizeof(Motor_Board_Index2010[0]), 0x2010},
  { (subindex*)Motor_Board_Index2011,sizeof(Motor_Board_Index2011)/sizeof(Motor_Board_Index2011[0]), 0x2011},
  { (subindex*)Motor_Board_Index2020,sizeof(Motor_Board_Index2020)/sizeof(Motor_Board_Index2020[0]), 0x2020},
  { (subindex*)Motor_Board_Index2021,sizeof(Motor_Board_Index2021)/sizeof(Motor_Board_Index2021[0]), 0x2021},
  { (subindex*)Motor_Board_Index2022,sizeof(Motor_Board_Index2022)/sizeof(Motor_Board_Index2022[0]), 0x2022},
  { (subindex*)Motor_Board_Index2023,sizeof(Motor_Board_Index2023)/sizeof(Motor_Board_Index2023[0]), 0x2023},
  { (subindex*)Motor_Board_Index2024,sizeof(Motor_Board_Index2024)/sizeof(Motor_Board_Index2024[0]), 0x2024},
  { (subindex*)Motor_Board_Index2025,sizeof(Motor_Board_Index2025)/sizeof(Motor_Board_Index2025[0]), 0x2025},
};

const indextable * Motor_Board_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1017: i = 2;*callbacks = Motor_Board_Index1017_callbacks; break;
		case 0x1018: i = 3;break;
		case 0x1200: i = 4;break;
		case 0x1280: i = 5;break;
		case 0x1281: i = 6;break;
		case 0x1282: i = 7;break;
		case 0x1283: i = 8;break;
		case 0x1284: i = 9;break;
		case 0x1285: i = 10;break;
		case 0x1400: i = 11;break;
		case 0x1401: i = 12;break;
		case 0x1402: i = 13;break;
		case 0x1403: i = 14;break;
		case 0x1600: i = 15;break;
		case 0x1601: i = 16;break;
		case 0x1602: i = 17;*callbacks = Motor_Board_Index1602_callbacks; break;
		case 0x1603: i = 18;break;
		case 0x1800: i = 19;*callbacks = Motor_Board_Index1800_callbacks; break;
		case 0x1801: i = 20;*callbacks = Motor_Board_Index1801_callbacks; break;
		case 0x1802: i = 21;*callbacks = Motor_Board_Index1802_callbacks; break;
		case 0x1803: i = 22;*callbacks = Motor_Board_Index1803_callbacks; break;
		case 0x1A00: i = 23;break;
		case 0x1A01: i = 24;break;
		case 0x1A02: i = 25;break;
		case 0x1A03: i = 26;break;
		case 0x2010: i = 27;break;
		case 0x2011: i = 28;break;
		case 0x2020: i = 29;break;
		case 0x2021: i = 30;break;
		case 0x2022: i = 31;break;
		case 0x2023: i = 32;break;
		case 0x2024: i = 33;break;
		case 0x2025: i = 34;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &Motor_Board_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Motor_Board_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index Motor_Board_firstIndex = {
  4, /* SDO_SVR */
  5, /* SDO_CLT */
  11, /* PDO_RCV */
  15, /* PDO_RCV_MAP */
  19, /* PDO_TRS */
  23 /* PDO_TRS_MAP */
};

const quick_index Motor_Board_lastIndex = {
  4, /* SDO_SVR */
  10, /* SDO_CLT */
  14, /* PDO_RCV */
  18, /* PDO_RCV_MAP */
  22, /* PDO_TRS */
  26 /* PDO_TRS_MAP */
};

const UNS16 Motor_Board_ObjdictSize = sizeof(Motor_Board_objdict)/sizeof(Motor_Board_objdict[0]); 

CO_Data Motor_Board_Data = CANOPEN_NODE_DATA_INITIALIZER(Motor_Board);

