#############################################################################
# Generated by PAGE version 4.2
# in conjunction with Tcl version 8.6
#    Feb. 12, 2014 08:13:11 PM


vTcl:font:add_GUI_font font10 \
"-family {DejaVu Sans} -size 16 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font font11 \
"-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top32
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    set site_4_0 .top32.tPa33.f1 
    set site_4_0 $site_4_0
    set site_5_0 $site_4_0.tSc35
    set site_4_1 .top32.tPa33.f2 
    set site_4_0 $site_4_1
    set site_5_0 $site_4_0.tSc34
    set site_4_2 .top32.tPa33.f3 
    set site_4_0 $site_4_2
    set site_5_0 $site_4_0.scr32
    set site_3_0 $base.m32
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow. {base} {
    if {$base == ""} {
        set base .
    }
    ###################
    # CREATING WIDGETS
    ###################
    wm focusmodel $top passive
    wm geometry $top 1x1+0+0; update
    wm maxsize $top 1905 1170
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm withdraw $top
    wm title $top "page.tcl"
    bindtags $top "$top Page.tcl all"
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top32 {base} {
    if {$base == ""} {
        set base .top32
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -menu "$top.m32" -background {#d9d9d9} -highlightbackground wheat \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 609x605+617+155; update
    wm maxsize $top 1905 1170
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Vrex for Python"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    bindtags $top "$top Toplevel all _TopLevel"
    ttk::style configure TPanedwindow -background #d9d9d9
    ttk::style configure TPanedwindow -foreground #000000
    ttk::style configure TPanedwindow -font font10
    ttk::style configure TPanedwindow -background #d9d9d9
    ttk::style configure TPanedwindow.Label -background #d9d9d9
    ttk::style configure TPanedwindow.Label -foreground #000000
    ttk::style configure TPanedwindow.Label -font font10
    ttk::panedwindow $top.tPa33 \
        -width 585 -height 500 
    vTcl:DefineAlias "$top.tPa33" "TPanedwindow1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font font10
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tPa33.f1 \
        -text {Regular Expression} -height 75 
    vTcl:DefineAlias "$top.tPa33.f1" "TPanedwindow1_f1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $top.tPa33.f1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_0.tSc35 \
        -background wheat -height 75 -highlightbackground wheat \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_4_0.tSc35" "Expression" vTcl:WidgetProc "Toplevel1" 1

    .top32.tPa33.f1.tSc35.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground wheat \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    place $site_4_0.tSc35 \
        -in $site_4_0 -x 10 -y 15 -width 561 -height 56 -anchor nw \
        -bordermode ignore 
    grid columnconf $site_4_0.tSc35 0 -weight 1
    grid rowconf $site_4_0.tSc35 0 -weight 1
    $top.tPa33 add $top.tPa33.f1 
        
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font font10
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tPa33.f2 \
        -text Sample -height 75 
    vTcl:DefineAlias "$top.tPa33.f2" "TPanedwindow1_f2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_1 $top.tPa33.f2
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_1.tSc34 \
        -background wheat -height 75 -highlightbackground wheat \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_4_1.tSc34" "Sample" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_1.tSc34 <Button-1> {
        sync_matches
    }

    .top32.tPa33.f2.tSc34.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 41 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    place $site_4_1.tSc34 \
        -in $site_4_1 -x 10 -y 15 -width 561 -height 50 -anchor nw \
        -bordermode ignore 
    grid columnconf $site_4_1.tSc34 0 -weight 1
    grid rowconf $site_4_1.tSc34 0 -weight 1
    $top.tPa33 add $top.tPa33.f2 
        
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font font10
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tPa33.f3 \
        -text Matches -height 56.0 
    vTcl:DefineAlias "$top.tPa33.f3" "TPanedwindow1_f3" vTcl:WidgetProc "Toplevel1" 1
    set site_4_2 $top.tPa33.f3
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_2.scr32 \
        -background wheat -height 75 -highlightbackground wheat \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_4_2.scr32" "Matches" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_2.scr32 <Button-1> {
        sync_sample
    }

    .top32.tPa33.f3.scr32.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 103 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    place $site_4_2.scr32 \
        -in $site_4_2 -x 10 -y 15 -width 561 -height 315 -anchor nw \
        -bordermode ignore 
    grid columnconf $site_4_2.scr32 0 -weight 1
    grid rowconf $site_4_2.scr32 0 -weight 1
    $top.tPa33 add $top.tPa33.f3 
        
    menu $top.m32 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground black -tearoff 1 
    $top.m32 add cascade \
        -menu "$top.m32.men33" -background {#d9d9d9} \
        -font {-family {Nimbus Sans L} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -label File 
    set site_3_0 $top.m32
    menu $site_3_0.men33 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground black -tearoff 0 
    $site_3_0.men33 add command \
        -background {#d9d9d9} -command load_regular_expression \
        -font {-family {Nimbus Sans L} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -label {Load regular expression} 
    $site_3_0.men33 add command \
        -background {#d9d9d9} -command save_regular_expression \
        -font {-family {Nimbus Sans L} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -label {Save regular expression} 
    $site_3_0.men33 add separator \
        -background {#d9d9d9} 
    $site_3_0.men33 add command \
        -background {#d9d9d9} -command load_sample \
        -font {-family {Nimbus Sans L} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -label {Load sample} 
    $site_3_0.men33 add command \
        -background {#d9d9d9} -command save_sample \
        -font {-family {Nimbus Sans L} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -label {Save sample} 
    $site_3_0.men33 add separator \
        -background {#d9d9d9} 
    $site_3_0.men33 add command \
        -background {#d9d9d9} -command quit \
        -font {-family {Nimbus Sans L} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -label Quit 
    $top.m32 add command \
        -background {#d9d9d9} -command help \
        -font {-family {Nimbus Sans L} -size 14 -weight normal -slant roman -underline 0 -overstrike 0} \
        -label Help 
    button $top.but34 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command quit -disabledforeground {#b8a786} \
        -foreground black -highlightbackground wheat -highlightcolor black \
        -text Quit 
    vTcl:DefineAlias "$top.but34" "Quit" vTcl:WidgetProc "Toplevel1" 1
    button $top.but32 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command lambda:display(0) \
        -disabledforeground {#b8a786} -foreground black \
        -highlightbackground wheat -highlightcolor black -text Match 
    vTcl:DefineAlias "$top.but32" "Match" vTcl:WidgetProc "Toplevel1" 1
    button $top.but33 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -command lambda:display(1) \
        -disabledforeground {#b8a786} -foreground blue \
        -highlightbackground wheat -highlightcolor black -text 1 
    vTcl:DefineAlias "$top.but33" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but35 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -command lambda:display(2) \
        -disabledforeground {#b8a786} -foreground darkgreen \
        -highlightbackground wheat -highlightcolor black -text 2 
    vTcl:DefineAlias "$top.but35" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but36 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -command lambda:display(3) \
        -disabledforeground {#b8a786} -foreground magenta \
        -highlightbackground wheat -highlightcolor black -text 3 
    vTcl:DefineAlias "$top.but36" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but37 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -command lambda:display(4) \
        -disabledforeground {#b8a786} -foreground sienna \
        -highlightbackground wheat -highlightcolor black -text 4 
    vTcl:DefineAlias "$top.but37" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button $top.but38 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -command lambda:display(5) \
        -disabledforeground {#b8a786} -foreground purple \
        -highlightbackground wheat -highlightcolor black -text 5 
    vTcl:DefineAlias "$top.but38" "Button5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -command lambda:display(6) \
        -disabledforeground {#b8a786} -foreground firebrick \
        -highlightbackground wheat -highlightcolor black -text 6 
    vTcl:DefineAlias "$top.but39" "Button6" vTcl:WidgetProc "Toplevel1" 1
    button $top.but40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -command lambda:display(7) \
        -disabledforeground {#b8a786} -foreground deeppink \
        -highlightbackground wheat -highlightcolor black -text 7 
    vTcl:DefineAlias "$top.but40" "Button7" vTcl:WidgetProc "Toplevel1" 1
    button $top.but41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -command lambda:display(8) \
        -disabledforeground {#b8a786} -foreground green4 \
        -highlightbackground wheat -highlightcolor black -text 8 
    vTcl:DefineAlias "$top.but41" "Button8" vTcl:WidgetProc "Toplevel1" 1
    button $top.but42 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -command lambda:display(9) \
        -disabledforeground {#b8a786} -foreground deepskyblue1 \
        -highlightbackground wheat -highlightcolor black -text 9 
    vTcl:DefineAlias "$top.but42" "Button9" vTcl:WidgetProc "Toplevel1" 1
    button $top.but43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command go -disabledforeground {#b8a786} \
        -foreground black -highlightbackground wheat -highlightcolor black \
        -text Go 
    vTcl:DefineAlias "$top.but43" "Go" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TSizegrip -background #d9d9d9
    vTcl::widgets::ttk::sizegrip::CreateCmd $top.tSi34 \
        -cursor bottom_right_corner 
    vTcl:DefineAlias "$top.tSi34" "TSizegrip1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tPa33 \
        -in $top -x 20 -y 10 -width 585 -height 500 -anchor nw \
        -bordermode ignore 
    place $top.but34 \
        -in $top -x 550 -y 550 -anchor nw -bordermode ignore 
    place $top.but32 \
        -in $top -x 100 -y 550 -anchor nw -bordermode ignore 
    place $top.but33 \
        -in $top -x 170 -y 550 -anchor nw -bordermode ignore 
    place $top.but35 \
        -in $top -x 210 -y 550 -anchor nw -bordermode ignore 
    place $top.but36 \
        -in $top -x 250 -y 550 -anchor nw -bordermode ignore 
    place $top.but37 \
        -in $top -x 290 -y 550 -anchor nw -bordermode ignore 
    place $top.but38 \
        -in $top -x 330 -y 550 -anchor nw -bordermode ignore 
    place $top.but39 \
        -in $top -x 370 -y 550 -anchor nw -bordermode ignore 
    place $top.but40 \
        -in $top -x 410 -y 550 -anchor nw -bordermode ignore 
    place $top.but41 \
        -in $top -x 450 -y 550 -anchor nw -bordermode ignore 
    place $top.but42 \
        -in $top -x 490 -y 550 -anchor nw -bordermode ignore 
    place $top.but43 \
        -in $top -x 30 -y 550 -anchor nw -bordermode ignore 
    place $top.tSi34 \
        -in $top -x 0 -relx 1 -y 0 -rely 1 -anchor se -bordermode inside 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top32

